services:
  # Aplicação Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digital-courses-app
    container_name: digital-courses-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      # Virtualização para performance:
      - /var/www/vendor
      - /var/www/node_modules
    networks:
      - digital-courses-network
    depends_on:
      - db
      - redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: digital-courses-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      # O Nginx também precisa ignorar essas pastas para não tentar ler do host
      - /var/www/vendor
      - /var/www/node_modules
    networks:
      - digital-courses-network
    depends_on:
      - app

  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: digital-courses-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - digital-courses-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: digital-courses-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - digital-courses-network

  # pgAdmin (UI para PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: digital-courses-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - digital-courses-network
    depends_on:
      - db

  # MinIO (S3 self-hosted)
  minio:
    image: minio/minio:latest
    container_name: digital-courses-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    command: server /data --console-address ":9001"
    networks:
      - digital-courses-network

  # Node.js para Vite
  node:
    image: node:20-alpine
    container_name: digital-courses-node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # Virtualiza a node_modules para o npm rodar na velocidade do Linux
      - /var/www/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - digital-courses-network

networks:
  digital-courses-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  minio_data:
    driver: local
